### ISSUE TITLE
make doesn't install ffmscompat.h when do make install

### ISSUE THREAD

**Issue by sl1pkn07** [qyot27/ffms2#1]
Hi

when build the project with configure and do make install, the file `ffmscompat.h` is not installed

generated `GNUakefile` only points to `ffms2.h`, but not for `ffms2compat.h`

greetings

**Comment by qyot27** [comment]
Fixed in https://github.com/qyot27/ffms2_cplugin/commit/c9a5370489193ddb45d5deca3d5e3f13b1a2b5a0
